
DROP TABLE IF EXISTS DEPARTMENT;
-- Create DEPARTMENT Table
CREATE TABLE DEPARTMENT(dept_no varchar(20) NOT NULL,dept_name varchar(20),PRIMARY KEY(dept_no));

LOAD DATA LOCAL INFILE  '/home/anabig114227/departments.csv'
INTO TABLE DEPARTMENT
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS DEPT_EMPLOYEE;
-- Create DEPT_EMPLOYEE Table
CREATE TABLE DEPT_EMPLOYEE(emp_no int NOT NULL,dept_no varchar(10), PRIMARY KEY(emp_no));

LOAD DATA LOCAL INFILE  '/home/anabig114227/dept_emp.csv'
INTO TABLE DEPT_EMPLOYEE
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS DEPT_MANAGER;
-- Create DEPT_MANAGER Table
CREATE TABLE DEPT_MANAGER(dept_no varchar(10),emp_no int);

LOAD DATA LOCAL INFILE  '/home/anabig114227/dept_manager.csv'
INTO TABLE DEPT_MANAGER
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS EMPLOYEES;
-- Create EMPLOYEES Table
CREATE TABLE EMPLOYEES(emp_no int NOT NULL,emp_title_id VARCHAR(10),birth_date VARCHAR(12),
			first_name VARCHAR(15),last_name VARCHAR(15),sex CHAR(2),
			hire_date VARCHAR(12),no_of_projects int,Last_performance_rating VARCHAR(5)
			,left_ VARCHAR(10),last_date VARCHAR(12),PRIMARY KEY(emp_no)
			);

LOAD DATA LOCAL INFILE  '/home/anabig114227/employees.csv'
INTO TABLE EMPLOYEES
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS SALARIES;
-- Create SALARIES Table
CREATE TABLE SALARIES(emp_no int,salary INT,PRIMARY KEY(emp_no));

LOAD DATA LOCAL INFILE  '/home/anabig114227/salaries.csv'
INTO TABLE SALARIES
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS TITLES;
-- Create TITLES Table
CREATE TABLE TITLES(title_id VARCHAR(10),title VARCHAR(10),PRIMARY KEY(title_id));

LOAD DATA LOCAL INFILE  '/home/anabig114227/titles.csv'
INTO TABLE TITLES
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
IGNORE 1 ROWS;








